### ISSUE TITLE
variable Packed BCD fields

### ISSUE THREAD

**Issue by pvanoppen** [chochos/j8583#44]
Hi, 
I need to generate (binary) mesagges that use variable length fields in packed BCD. The first byte should specify the length of the field in nibbles (4bit values), rather than bytes:
"6273" to be encoded in 4 nibbles or 3 bytes: <code> 04 62 73 </code> 
"98765" with 5 nibbles is to be be encoded in 4 bytes: <code> 05 98 76 50 </code>
Note the that the last nibble is set to 0 to round up to a whole amount of bytes, The field size, shown in the first byte, will be less than 255 nibbles and is a regular number (0..255), not BCD. 

Using the <b>LLBIN</b> type I get close, but the first field specifies the amount of bytes, rather than the amount of nibbles, and odd sized fields are prepended with a 0, which is undesired:
"1234" is encoded as <code><b>02</b> 12 34 </code>. 
"98765" is encoded as <code><b>03</b> 09 87 65 </code>

Is there a way to use/configure one of the standard ISOtypes (like LLBIN or LLVAR) or do I need to implemement a new type (LLBCD)?

Paul

**Comment by chochos** [comment]
You can write your own `CustomField` that encodes using LLBIN and then just replace the field's length header...

**Comment by rajasekarchinna** [comment]
Hi chochos,
I am also facing same issue
We cant change length using CustomField since writeLengthHeader is invoked from write methos in ISOValue
LLBIN for Number field - Shoul display number of nibble in length field and should suffix pad character at end and it should be F as per specification Please suggest

**Comment by rajasekarchinna** [comment]
Hi chochos,
I am also facing same issue
We cant change length using CustomField since writeLengthHeader is invoked from write methos in ISOValue
LLBIN for Number field - Shoul display number of nibble in length field and should suffix pad character at end and it should be F as per specification Please suggest

**Comment by rajasekarchinna** [comment]
Hi chochos,
I am also facing same issue
We cant change length using CustomField since writeLengthHeader is invoked from write methos in ISOValue
LLBIN for Number field - Shoul display number of nibble in length field and should suffix pad character at end and it should be F as per specification Please suggest

**Comment by rajasekarchinna** [comment]
How to replace field's length header since it is handle in writeLengthHeader method in IsoValue class Please clarify

**Comment by rajasekarchinna** [comment]
How to replace field header length since it is not accessible from CustomField implementation

**Comment by rajasekarchinna** [comment]
How to replace field header length,length is calculated and write to bytes in writeLength method of IsoValue class

**Comment by chochos** [comment]
If you can point me to any place in the ISO8583 standard where this is mentioned as being part of it, then we can implement it as a new datatype, or modify the library in some way so that variable-length binary fields can be configured to encode and parse their length in nibbles instead of bytes.

Otherwise you'll need to implement your own datatype LLBCD as you mentioned. You'll need to modify IsoType and create your own parsers for the field, at the very least.

**Comment by pvanoppen** [comment]
I do not have a ISO8583 specification around, however, and I doubt that this is somewhere mentioned.  I did end up creating a VNUMBCD type, which is implemented as a child class of LLBIN type. 
As it is not an official type, I had to code some work a rounds to make it work. 
I did not add support for the xml configuration parsing, so I created the parseMap programmatically to be able to receive response messages:
    parseMap.put(2, createFPI("VNUMBCD",0,encoding));
    parseMap.put(3, createFPI("NUMERIC",6,encoding));
    ...
     mfact.setParseMap(0x210, parseMap);

Note that I would have preferred just to update the parseMap created by the xml configuration, but there's no mfact.getParseMap... 

createFPI is a helper method to create a FieldParseInfo (FPI) object with support for proprietary IsoValue type <b>VNUMBCD</b>. This type binds the Llbin_VNumBcdParseInfo()  class, which I wrote as an extension of the LlbinParseInfo class, overriding the parseBinary method to do the actual BCD parsing.

I also wrote IsoValueLLBIN_VNUMBCD (a child class of IsoValue) to support a variable length numeric BCD encoded field. This way I could swap the fields created by the template to the ones that were BCD encoded:
            IsoMessage req = mfact.newMessage(0x200);
            req.setBinary(true);
            req.setField(2, new IsoValueLLBIN_VNUMBCD<Object>(req.getField(2)));

the solution was not very elegant, but it worked.

**Comment by rajasekarchinna** [comment]
Hi Can you share your implementation

**Comment by rajasekarchinna** [comment]
Have you uploaded your changes in GitHub? Can you share your changes?

**Comment by pvanoppen** [comment]
I am not allowed to publish the message formats, but I can give you the relevant classes (see attachment) and the Client.java demo source, which gives an example how to use the classes.    
[iso8583patch.zip](https://github.com/chochos/j8583/files/83478/iso8583patch.zip)
Good luck

**Comment by stevegreen22** [comment]
Really sucks to be subscribed to this right now. Jfc
